const menu1 = [
    {
        key: '0', label: 'INFO', url: '',
        children: [
            { key: '0-1', label: 'Bank', url: 'S0110_KCD_BANK_QRY', children: [] },
            { key: '0-2', label: 'User', url: 'S0111_KCD_USER', children: []},
            { key: '0-3', label: 'Size', url: 'S0107_KCD_SIZEMST', children: []},
            { key: '0-4', label: 'Buyer', url: 'S0113_KCD_BUYER', children: []},
            { key: '0-5', label: 'Supplier', url: 'S0114_KCD_SUPPLIER', children: []},
            { key: '0-6', label: 'Factory', url: 'S0101_KCD_FACTORY', children: []},
            { key: '0-7', label: 'Forwarder', url: 'S0108_KCD_PLACE', children: []},
            { key: '0-8', label: 'HS Code', url: 'S0105_KCD_HSCODE', children: []},
            { key: '0-9', label: 'Currency', url: 'S0112_KCD_CURRENCY', children: []},
            { key: '0-10', label: 'Currency for Price', url: 'S0218_EXCHANGE_RATE_RECORD', children: []},
            { key: '0-11', label: 'Country', url: 'S0104_KCD_NATION', children: []},
            /* { key: '0-12', label: 'Loss', url: '', children: []}, */
        ]
    },
    {
        key: '1', label: 'ORDER', url: '', 
        children: [
            { key: '1-1', label: 'Style Regist', url: 'S0200_KCD_STYLE' },
            { key: '1-2', label: 'Style Price', url: 'S0202_STYLE_COST' },
            { key: '1-4', label: 'Order Manager', url: 'S0204_ORDER_LIST'},
            { key: '1-19', label: 'Order Regist', url: 'S020602_ORDER_REG'},
            { key: '1-6', label: 'PO Manager', url: 'S020701_PO_MANAGER'},
            { key: '1-8', label: 'PI Manager', url: 'S0205_PI_MANAGER'},
            { key: '1-9', label: 'Capa Record', url: 'S0208_CAPABOOK_RECORD_BVT'},
            { key: '1-10', label: 'Capa List', url: 'S0209_CAPABOOK_LIST_BVT'},
            { key: '1-14', label: '손익현황', url: 'S0213_ORDER_REPORT'},
            { key: '1-15', label: 'Order Status', url: 'S0214_ORDER_STATUS_BEFORE_AFTER_CHECK'},
            { key: '1-16', label: 'Over/Shortage', url: 'S0215_ORDER_STATUS_SHORTAGE'},
            { key: '1-17', label: 'Sales Plan(Record)', url: 'S0216_SALES_MATL_PLAN_QRY'},
            { key: '1-18', label: 'Sales Plan(List)', url: 'S0217_SALES_MATL_PLAN_LIST'}
        ]
    },
    {
        key: '2', label: 'MRP', url: '',
        children: [
            { key: '2-1', label: 'Material Record', url: 'S0301_MATL_RECORD' },
            { key: '2-2', label: 'Material Search', url: 'S0302_MATL_SEARCH'},
            { key: '2-3', label: 'MRP Record(Style)', url: 'S0303_MRP_RECORD_STYLE'},
            { key: '2-4', label: 'MRP Manager', url: 'S0305_MRP_MANAGER'},
            { key: '2-6', label: 'MRP Record(Order)', url: 'S0306_MRP_BY_ORDER'}
        ]
    },
    {
        key: '3', label: 'PURCHASE', url: '',
        children: [
            { key: '3-1', label: 'Purchase Manager', url: 'S0401_PURCHASING_MANAGER' },
            { key: '3-2', label: 'Purchase Reg', url: 'S040101_PURCHASER_REG' },
            { key: '3-4', label: 'STSIN List', url: 'S043001_STSIN_LIST'},
            { key: '3-6', label: 'STSOUT List', url: 'S043101_STSOUT_LIST'},
            { key: '3-3', label: 'Deposit & L/C Manager', url: 'S0439_LC_DEPOSIT'},
            { key: '3-7', label: 'Bill Regist', url: 'S0419_ENDDING_MATL_AMT_DOMESTIC'},
            { key: '3-8', label: 'Bill Manager', url: 'S0423_TAXBILL'}
        ]
    },
    {
        key: '4', label: 'EXPORT/IMPORT', url: '',
        children: [
            { key: '4-1', label: 'Shipment Manager', url: 'S0434_SHIPMENT_MANAGER' },
            /* { key: '4-2', label: '수출등록(국내)', url: 'S0437_EXPORT_REGIST'}, */
            { key: '4-3', label: '수입등록(국내)', url: 'S0438_IMPORT_REGIST'},
            { key: '4-8', label: 'Garment Ship', url: 'S0513_SHIPPING_LIST'},
            { key: '4-7', label: 'Delay Report', url: 'S0450_DELAY_REPORT'}
        ]
    },
    {
        key: '5', label: 'FACTORY IN-OUT', url: '',
        children: [
            { key: '5-2', label: 'Clearance_Arrival(BVT)', url: 'S0518_FACTORY_ARRIVAL?FACTORY=BVT' },
            { key: '5-17', label: 'Clearance_Arrival(ETP)', url: 'S0518_FACTORY_ARRIVAL?FACTORY=ETP' },
            { key: '5-3', label: 'FAC-IN(Inspection)', url: 'S0519_INSPECT_REPORT' },
            { key: '5-4', label: 'FAC-IN List', url: 'S051901_FACIN_LIST' },
            { key: '5-5', label: 'Stock Confirm', url: 'S0516_STOCK_USE_CONFIRM' },
            { key: '5-6', label: 'Fac-Out Record', url: 'S0520_FACOUT_RECORD' },
            { key: '5-7', label: 'Fac-Out List', url: 'S052001_FACOUT_LIST' },
            { key: '5-8', label: 'Production Finish', url: 'S0508_CAPABOOK_LIST_BVT' },
            { key: '5-9', label: 'Line Return', url: 'S0509_RETURN_MATL' },
            { key: '5-10', label: 'Pending Shipment', url: 'S0531_PENDDING_SHIPMENT' },
            { key: '5-11', label: 'Stock Record', url: 'S0521_STOCK_RECORD_NEW' },
            { key: '5-12', label: 'Stock Manager', url: 'S0523_STOCK_MANAGER' },
        ]
    },
    {
        key: '6', label: 'COST', url: '',
        children: [
            { key: '6-1', label: 'Cost Confirmation', url: 'S0610_COST_CONFIRM' },
            { key: '6-2', label: 'CMPT Payment', url: 'S0705_CMPT_PAYMENT' },
            { key: '6-3', label: 'Credit Note', url: 'S0701_CREDIT_NOTE'},
            { key: '6-4', label: 'Debit Note', url: 'S0702_DEBIT_NOTE'},
            { key: '6-5', label: 'Debit Note(BVT)', url: 'S0703_DEBIT_NOTE_FACTORY_BVT'},
            { key: '6-7', label: 'Debit Note(E)', url: 'S070301_DEBIT_NOTE_FACTORY_ETP'},
            { key: '6-8', label: 'Sample Cost', url: 'S0203_SAMPLE_COST' },
            { key: '6-9', label: 'CMPT Confirmation', url: 'S0212_NEGO_CMPT'},
        ]
    },
    {
        key: '7', label: 'RECEIVABLES', url: '',
        children: [
            { key: '7-2', label: '매출등록(국내)', url: 'S0801_DOCU_REGIST_DOMESTIC' },
            { key: '7-3', label: 'Invoice Record(Foreign)', url: 'S0802_DOCU_REGIST_OVERSEA' },
            { key: '7-5', label: 'Nego입금등록', url: 'S0607_LC_NEGO'},
            { key: '7-7', label: '매출입금관리', url: 'S0707_MAN_INVOICE'},
            { key: '7-6', label: '입금조회', url: 'S0608_LC_NEGO_LIST'},
            { key: '7-8', label: '바이어별입금관리', url: 'S0708_MANAGE_BUYER_INPUT'},
            { key: '7-9', label: '매출채권조회', url: 'S0709_MANAGE_INVOICE_AMT'},
            /*{ key: '7-10', label: '(#)오더수불부', url: 'S0710_ORDER_EXPORT_REPORT'}*/
        ]
    }
];

const menu3 = [
    { key: '0-1', label: 'Bank', url: 'S0110_KCD_BANK_QRY', children: [] },
    { key: '0-2', label: 'User', url: 'S0111_KCD_USER', children: []},
    { key: '0-3', label: 'Size', url: 'S0107_KCD_SIZEMST', children: []},
    { key: '0-4', label: 'Buyer', url: 'S0113_KCD_BUYER', children: []},
    { key: '0-5', label: 'Suuplier', url: 'S0114_KCD_SUPPLIER', children: []},
    { key: '0-6', label: 'Factory', url: 'S0101_KCD_FACTORY', children: []},
    { key: '0-7', label: 'Forwarder', url: 'S0108_KCD_PLACE', children: []},
    { key: '0-8', label: 'HS Code', url: 'S0105_KCD_HSCODE', children: []},
    { key: '0-9', label: 'Currency', url: 'S0112_KCD_CURRENCY', children: []},
    { key: '0-10', label: 'Currency for Price', url: 'S0218_EXCHANGE_RATE_RECORD', children: []},
    { key: '0-11', label: 'Country', url: 'S0104_KCD_NATION', children: []},
    { key: '0-12', label: 'Loss', url: '', children: []},
    { key: '1-1', label: 'Style Regist', url: 'S0200_KCD_STYLE' },
    { key: '1-2', label: 'Style Cost', url: 'S0202_STYLE_COST' },
    { key: '1-3', label: 'Sample Cost', url: 'S0203_SAMPLE_COST' },
    { key: '1-4', label: 'Order Manager', url: 'S0204_ORDER_LIST'},
    { key: '1-19', label: 'Order Regist', width:'1365px', height:'800px', url: 'S020602_ORDER_REG'},
    { key: '1-20', label: 'Order Info', width:'1365px', height:'800px', url: 'S020602_ORDER_REG'},
    { key: '1-6', label: 'PO Manager', url: 'S020701_PO_MANAGER'},
    { key: '1-8', label: 'PI Manager', url: 'S0205_PI_MANAGER'},
    { key: '1-9', label: 'Capa Record', url: 'S0208_CAPABOOK_RECORD_BVT'},
    { key: '1-10', label: 'Capa List', url: 'S0209_CAPABOOK_LIST_BVT'},
    { key: '1-13', label: 'CMPT Confirmation', url: 'S0212_NEGO_CMPT'},
    { key: '1-14', label: '손익현황', url: 'S0213_ORDER_REPORT'},
    { key: '1-15', label: 'Order Status', url: 'S0214_ORDER_STATUS_BEFORE_AFTER_CHECK'},
    { key: '1-16', label: 'Over/Shortage', url: 'S0215_ORDER_STATUS_SHORTAGE'},
    { key: '1-17', label: 'Sales Plan(Record)', url: 'S0216_SALES_MATL_PLAN_QRY'},
    { key: '1-18', label: 'Sales Plan(List)', url: 'S0217_SALES_MATL_PLAN_LIST'},
    { key: '2-1', label: 'Material Record', url: 'S0301_MATL_RECORD' },
    { key: '2-2', label: 'Material Search', url: 'S0302_MATL_SEARCH'},
    { key: '2-3', label: 'MRP Record(Style)', url: 'S0303_MRP_RECORD_STYLE'},
    { key: '2-20', label: 'Copy Product', url: 'S030301_COPY_PRODUCT'},
    { key: '2-21', label: 'Style Mrp Search', url: 'S030302_COPY_STYLE'},
    { key: '2-22', label: 'Order Mrp Search', url: 'S030303_MRP_BY_SEARCH'},
    { key: '2-4', label: 'MRP Manager', url: 'S0305_MRP_MANAGER'},
    { key: '2-6', label: 'Seq Delete', url: 'S030501_DEL_MRP_PACK'},
    { key: '2-7', label: 'Po History', url: 'S030502_PO_HISTORY'},
    { key: '2-25', label: 'MRP List', url: 'S030513_MRP_LIST'},
    { key: '2-26', label: 'PO List', url: 'S030514_PO_LIST'},
    { key: '2-27', label: 'MRP Pack Down', url: 'S030515_MRP_PACK'},
    { key: '2-8', label: 'Stock Check', url: 'S030503_STOCK_CHECK'},
    { key: '2-9', label: 'PO Revise', url: 'S030504_REVISE'},
    { key: '2-10', label: 'Matl Add', url: 'S030505_PO_RECORD_MATL_ADD'},
    { key: '2-11', label: 'PO Regist(Material)', url: 'S030506_NEW_PO_SAMPLE'},
    { key: '2-12', label: 'Make MRP', url: 'S030510_PO_MAKE_MRP'},
    { key: '2-13', label: 'Make MRP(F)', url: 'S030512_PO_MAKE_MRP_FIRST'},
    { key: '2-14', label: 'PO History2', url: 'S030511_PO_HISTORY2'},
    { key: '2-5', label: 'MRP Record(Order)', url: 'S0306_MRP_BY_ORDER'},
    { key: '2-24', label: 'Style MRP Search(Order)', url: 'S030602_MRP_BY_ORDER_STYLE'},
    { key: '3-1', label: 'Purchase Manager', url: 'S0401_PURCHASING_MANAGER' },
    { key: '3-12', label: 'Purchase Monitor', url: 'S040100_PUR_MONITOR' },
    { key: '3-10', label: 'Purchase Reg', url: 'S040101_PURCHASER_REG' },
    { key: '3-11', label: 'Purchase Info', url: 'S040102_PURCHASER_INFO' },
    { key: '3-2', label: 'STSIN Record', url: 'S0430_STSIN_RECORD'},
    { key: '3-4', label: 'STSIN List', url: 'S043001_STSIN_LIST'},
    { key: '3-5', label: 'STSOUT Record', url: 'S0431_STSOUT_RECORD'},
    { key: '3-6', label: 'STSOUT List', url: 'S043101_STSOUT_LIST'},
    { key: '3-3', label: 'Deposit & L/C Manager', url: 'S0439_LC_DEPOSIT'},
    { key: '3-7', label: 'Bill Regist', url: 'S0419_ENDDING_MATL_AMT_DOMESTIC'},
    { key: '3-8', label: 'Bill Manager', url: 'S0423_TAXBILL'},
    { key: '4-1', label: 'Shipment Manager', url: 'S0434_SHIPMENT_MANAGER' },
    { key: '4-10', label: 'Shipment Reg', url: 'S0433_SHIPMENT_REGIST' },
    { key: '4-11', label: 'Shipment Info', url: 'S043401_SHIPMENT_INFO' },
    { key: '4-12', label: 'Freight Reg', url: 'S0440_FREIGHT_REGIST' },
    { key: '4-13', label: 'Shiping Cost', url: 'S0435_SHIPPING_COST' },
    { key: '4-14', label: 'Local Cost', url: 'S0436_LOCAL_COST' },
    { key: '4-15', label: 'STSIN_INFO', url: 'S043002_STSIN_INFO' },
    { key: '4-2', label: '수출등록(국내)', url: 'S0437_EXPORT_REGIST'},
    { key: '4-3', label: '수입등록(국내)', url: 'S0438_IMPORT_REGIST'},
    { key: '4-8', label: 'Garment Ship', url: 'S0513_SHIPPING_LIST'},
    { key: '4-16', label: 'Shipping Regist', url: 'S051301_SHIPPING_REGIST'},
    { key: '4-7', label: 'Delay Report(#)', url: 'S0450_DELAY_REPORT'},
    { key: '5-1', label: '관리메인(#)', url: '#' },
    { key: '5-2', label: 'Clearance_Arrival(BVT)', url: 'S0518_FACTORY_ARRIVAL?FACTORY=BVT' },
    { key: '5-17', label: 'Clearance_Arrival(ETP)', url: 'S0518_FACTORY_ARRIVAL?FACTORY=ETP' },
    { key: '5-3', label: 'FAC-IN(Inspection)', url: 'S0519_INSPECT_REPORT' },
    { key: '5-4', label: 'FAC-IN List', url: 'S051901_FACIN_LIST' },
    { key: '5-5', label: 'Stock Confirm', url: 'S0516_STOCK_USE_CONFIRM' },
    { key: '5-6', label: 'Fac-Out Record', url: 'S0520_FACOUT_RECORD' },
    { key: '5-7', label: 'Fac-Out List', url: 'S052001_FACOUT_LIST' },
    { key: '5-8', label: 'Production Finish', url: 'S0508_CAPABOOK_LIST_BVT' },
    { key: '5-9', label: 'Line Return', url: 'S0509_RETURN_MATL' },
    { key: '5-10', label: 'Pending Shipment', url: 'S0531_PENDDING_SHIPMENT' },
    { key: '5-11', label: 'Stock Record', url: 'S0521_STOCK_RECORD_NEW' },
    { key: '5-12', label: 'Stock Manager(#)', url: 'S0512_STOCK_LIST' },
    { key: '5-13', label: 'Stock I/O History', url: 'S0517_STOCK_HISTORY'},
    { key: '6-1', label: 'Cost Confirmation', url: 'S0610_COST_CONFIRM' },
    { key: '6-2', label: 'CMPT Payment', url: 'S0705_CMPT_PAYMENT' },
    { key: '6-3', label: 'Credit Note', url: 'S0701_CREDIT_NOTE'},
    { key: '6-4', label: 'Debit Note', url: 'S0702_DEBIT_NOTE'},
    { key: '6-5', label: 'Debit Note(BVT)', url: 'S0703_DEBIT_NOTE_FACTORY_BVT'},
    { key: '6-7', label: 'Debit Note(E)', url: 'S070301_DEBIT_NOTE_FACTORY_ETP'},
    { key: '6-8', label: 'Sample Cost', url: 'S0203_SAMPLE_COST' },
    { key: '6-9', label: 'CMPT Confirmation', url: 'S0212_NEGO_CMPT'},
    { key: '7-2', label: '매출등록(국내)', url: 'S0801_DOCU_REGIST_DOMESTIC' },
    { key: '7-11', label: '세금계산서등록', url: 'S080101_DOCU_REGIST_DOMESTIC' },
    { key: '7-3', label: 'Invoice Record(Foreign)', url: 'S0802_DOCU_REGIST_OVERSEA' },
    { key: '7-5', label: 'Nego입금등록', url: 'S0607_LC_NEGO'},
    { key: '7-7', label: '매출입금관리', url: 'S0707_MAN_INVOICE'},
    { key: '7-6', label: '입금조회', url: 'S0608_LC_NEGO_LIST'},
    { key: '7-8', label: '바이어별입금관리', url: 'S0708_MANAGE_BUYER_INPUT'},
    { key: '7-9', label: '매출채권조회', url: 'S0709_MANAGE_INVOICE_AMT'},
    /*{ key: '7-10', label: '(#)오더수불부', url: 'S0710_ORDER_EXPORT_REPORT'}*/
];

module.exports = {
    menu1,
    menu3,
}
